spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lotterysystem?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
mybatis:
  configuration:
    auto-mapping-behavior: full
  type-aliases-package: com.cssl.pojo
server:
  port: 8080
  servlet:
    context-path: /lotterySystem/